final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Yaar-O-Aghyaar',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Yaaro_Giyar/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Yaaro_Giyar/',
    'imageAsset': 'assets/parsi_title/urdu/1.png',
    'imageListAsset': 'assets/parsi_list/urdu/1.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Pas-E-Parda-E-Raaz',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Pase_Pardaye_Raaz/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Pase_Pardaye_Raaz/',
    'imageAsset': 'assets/parsi_title/urdu/2.png',
    'imageListAsset': 'assets/parsi_list/urdu/2.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Husn-E-Yaganaa',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Husne_Yagana/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Husne_Yagana/',
    'imageAsset': 'assets/parsi_title/urdu/3.png',
    'imageListAsset': 'assets/parsi_list/urdu/3.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Nawa-E-Shauq',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Nawaye_Showq/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Nawaye_Showq/',
    'imageAsset': 'assets/parsi_title/urdu/4.png',
    'imageListAsset': 'assets/parsi_list/urdu/4.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Makham-E-Aashiqaa',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Maqaame_Aashiqaan/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Maqaame_Aashiqaan/',
    'imageAsset': 'assets/parsi_title/urdu/5.png',
    'imageListAsset': 'assets/parsi_list/urdu/5.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Syed-Ul-Bashar ﷺ',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Syedul_BasharApril/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Syedul_BasharApril/',
    'imageAsset': 'assets/parsi_title/urdu/6.png',
    'imageListAsset': 'assets/parsi_list/urdu/6.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Shaheenshah-E-Wilayat',
    'webImageFolderPath': 'https://habibifoundation.org/wp-admin/kalam/urdu/Farsi/Shahishahe_Wilayath/',
    'webAudioBasePath': 'https://habibifoundation.org/kalam/urdu/Farsi/Shahishahe_Wilayath/',
    'imageAsset': 'assets/parsi_title/urdu/7.png',
    'imageListAsset': 'assets/parsi_list/urdu/7.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
];
