final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Yaar-O-Aghyaar',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Yaaro_Giyar/',
    'imageAsset': 'assets/parsi_title/urdu/1.png',
    'imageListAsset': 'assets/parsi_list/urdu/1.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Pas-E-Parda-E-Raaz',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Pase_Pardaye_Raaz/',
    'imageAsset': 'assets/parsi_title/urdu/2.png',
    'imageListAsset': 'assets/parsi_list/urdu/2.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Husn-E-Yaganaa',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Husne_Yagana/',
    'imageAsset': 'assets/parsi_title/urdu/3.png',
    'imageListAsset': 'assets/parsi_list/urdu/3.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Nawa-E-Shauq',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Nawaye_Showq/',
    'imageAsset': 'assets/parsi_title/urdu/4.png',
    'imageListAsset': 'assets/parsi_list/urdu/4.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Makham-E-Aashiqaa',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Maqaame_Aashiqaan/',
    'imageAsset': 'assets/parsi_title/urdu/5.png',
    'imageListAsset': 'assets/parsi_list/urdu/5.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Syed-Ul-Bashar ﷺ',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Syedul_Bashar/',
    'imageAsset': 'assets/parsi_title/urdu/6.png',
    'imageListAsset': 'assets/parsi_list/urdu/6.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Shaheenshah-E-Wilayat',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Shahishahe_Wilayath/',
    'imageAsset': 'assets/parsi_title/urdu/7.png',
    'imageListAsset': 'assets/parsi_list/urdu/7.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
];
