/* final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Yaar-O-Aghyaar',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Yaaro_Giyar/',
    'imageAsset': 'assets/parsi_title/english/1.png',
    'imageListAsset': 'assets/parsi_list/english/1.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Pas-E-Parda-E-Raaz',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Pase_Pardaye_Raaz/',
    'imageAsset': 'assets/parsi_title/english/2.png',
    'imageListAsset': 'assets/parsi_list/english/2.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Husn-E-Yaganaa',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Husne_Yagana/',
    'imageAsset': 'assets/parsi_title/english/3.png',
    'imageListAsset': 'assets/parsi_list/english/3.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Nawa-E-Shauq',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Nawaye_Showq/',
    'imageAsset': 'assets/parsi_title/english/4.png',
    'imageListAsset': 'assets/parsi_list/english/4.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Makham-E-Aashiqaa',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Maqaame_Aashiqaan/',
    'imageAsset': 'assets/parsi_title/english/5.png',
    'imageListAsset': 'assets/parsi_list/english/5.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Syed-Ul-Bashar ﷺ',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Syedul_Bashar/',
    'imageAsset': 'assets/parsi_title/english/6.png',
    'imageListAsset': 'assets/parsi_list/english/6.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Shaheenshah-E-Wilayat',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Shahishahe_Wilayath/',
    'imageAsset': 'assets/parsi_title/english/7.png',
    'imageListAsset': 'assets/parsi_list/english/7.png',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
];
 */
final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Yaar-O-Aghyaar',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Yaaro_Giyar/',
    'imageAsset': 'assets/parsi_title/english/1.png',
    'imageListAsset': 'Sanama Tu Jaan-E-Jahaan',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Pas-E-Parda-E-Raaz',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Pase_Pardaye_Raaz/',
    'imageAsset': 'assets/parsi_title/english/2.png',
    'imageListAsset': 'Tu Har Dam Yaad Mi Aayi',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Husn-E-Yaganaa',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Husne_Yagana/',
    'imageAsset': 'assets/parsi_title/english/3.png',
    'imageListAsset': 'Man Cheez-E-Na Bay Mann',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Nawa-E-Shauq',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Nawaye_Showq/',
    'imageAsset': 'assets/parsi_title/english/4.png',
    'imageListAsset': 'Daanam Ke Tuyi Hasti',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Makham-E-Aashiqaa',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Maqaame_Aashiqaan/',
    'imageAsset': 'assets/parsi_title/english/5.png',
    'imageListAsset': 'Kalam-E-Zaahidan Deegar',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Syed-Ul-Bashar ﷺ',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Syedul_Bashar/',
    'imageAsset': 'assets/parsi_title/english/6.png',
    'imageListAsset': 'Maariz-E-Tu’am Kun Dawa',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
  {
    'title': 'Shaheenshah-E-Wilayat',
    'firebaseImagePath': 'kalam/Qinde_Parsi/Shahishahe_Wilayath/',
    'imageAsset': 'assets/parsi_title/english/7.png',
    'imageListAsset': 'Reham Kun Behre Khudaa',
    'artistPaths': {},
    'appBarTitle': 'Qand-E-Farsi',
  },
];
