final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Rehbar-E-Kaamil',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Rahbare_Kamil/',
    'imageAsset': 'assets/noori_title/urdu/1.png',
    'imageListAsset': 'assets/noori_list/urdu/1.png',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/1.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Sipaas Nama',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Sipas_Nama/',
    'imageAsset': 'assets/noori_title/urdu/2.png',
    'imageListAsset': 'assets/noori_list/urdu/2.png',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Faizan-E-Nazar',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Faizan_e_Nazar/',
    'imageAsset': 'assets/noori_title/urdu/3.png',
    'imageListAsset': 'assets/noori_list/urdu/3.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Noori/3.mp3',
      'Imran': 'kalam/Audios/Imran/Noori/3.mp3',
    },
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Murshid Se Khitaab',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Mushid_Se_Khitab/',
    'imageAsset': 'assets/noori_title/urdu/4.png',
    'imageListAsset': 'assets/noori_list/urdu/4.png',
    'artistPaths': {
      'Imran': 'kalam/Audios/Imran/Noori/4.mp3',
      'Arif': 'kalam/Audios/Arif/Noori/4.mp3',
    },
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Peer Noori',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Peer_Noori/',
    'imageAsset': 'assets/noori_title/urdu/5.png',
    'imageListAsset': 'assets/noori_list/urdu/5.png',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Bargah-E-Mashkhiyath Panaa',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Ba_Bargahe_Mashiyath/',
    'imageAsset': 'assets/noori_title/urdu/6.png',
    'imageListAsset': 'assets/noori_list/urdu/6.png',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/6.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Yaad-E-Shaikh',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Yaade_Shaik/',
    'imageAsset': 'assets/noori_title/urdu/7.png',
    'imageListAsset': 'assets/noori_list/urdu/7.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Noori/7.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Dyar-E-Noori Ko Rawangi Se Pehle',
    'firebaseImagePath':
        'kalam/Munaqib_e_Noori/Dayare_Noori_Ko_Rawangi_se_Pehile/',
    'imageAsset': 'assets/noori_title/urdu/8.png',
    'imageListAsset': 'assets/noori_list/urdu/8.png',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Aye Eind Laib Chalke Chale Din Bahar Ke',
    'firebaseImagePath': 'kalam/Munaqib_e_Noori/Ay_Andalib_Chal_Ke/',
    'imageAsset': 'assets/noori_title/urdu/9.png',
    'imageListAsset': 'assets/noori_list/urdu/9.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Noori/9.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
];
