/* final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Rehbar-E-Kaamil',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Rahbare_Kamil/',
    'imageAsset': 'assets/noori_title/english/1.png',
    'imageListAsset': 'assets/noori_list/english/1.png',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/1.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Sipaas Nama',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Sipas_Nama/',
    'imageAsset': 'assets/noori_title/english/2.png',
    'imageListAsset': 'assets/noori_list/english/2.png',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Faizan-E-Nazar',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Faizan_e_Nazar/',
    'imageAsset': 'assets/noori_title/english/3.png',
    'imageListAsset': 'assets/noori_list/english/3.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Noori/3.mp3',
      'Imran': 'kalam/Audios/Imran/Noori/3.mp3',
    },
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Murshid Se Khitaab',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Mushid_Se_Khitab/',
    'imageAsset': 'assets/noori_title/english/4.png',
    'imageListAsset': 'assets/noori_list/english/4.png',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/4.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Peer Noori',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Peer_Noori/',
    'imageAsset': 'assets/noori_title/english/5.png',
    'imageListAsset': 'assets/noori_list/english/5.png',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Bargah-E-Mashkhiyath Panaa',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Ba_Bargahe_Mashiyath/',
    'imageAsset': 'assets/noori_title/english/6.png',
    'imageListAsset': 'assets/noori_list/english/6.png',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/6.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Yaad-E-Shaikh',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Yaade_Shaik/',
    'imageAsset': 'assets/noori_title/english/7.png',
    'imageListAsset': 'assets/noori_list/english/7.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Noori/7.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Dyar-E-Noori Ko Rawangi Se Pehle',
    'firebaseImagePath':
        'kalam/English/Munaqib_e_Noori/Dayare_Noori_Ko_Rawangi_se_Pehile/',
    'imageAsset': 'assets/noori_title/english/8.png',
    'imageListAsset': 'assets/noori_list/english/8.png',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Aye Eind Laib Chalke Chale Din Bahar Ke',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Ay_Andalib_Chal_Ke/',
    'imageAsset': 'assets/noori_title/english/9.png',
    'imageListAsset': 'assets/noori_list/english/9.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Noori/9.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
];
 */

final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Rehbar-E-Kaamil',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Rahbare_Kamil/',
    'imageAsset': 'assets/noori_title/english/1.png',
    'imageListAsset': 'Tujhse Jo Cheez Hai Mili',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/1.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Sipaas Nama',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Sipas_Nama/',
    'imageAsset': 'assets/noori_title/english/2.png',
    'imageListAsset': 'Mere Noori Piya Tere Isharoon',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Faizan-E-Nazar',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Faizan_e_Nazar/',
    'imageAsset': 'assets/noori_title/english/3.png',
    'imageListAsset': 'Mere Noor Wale Shaha',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Noori/3.mp3',
      'Imran': 'kalam/Audios/Imran/Noori/3.mp3',
    },
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Murshid Se Khitaab',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Mushid_Se_Khitab/',
    'imageAsset': 'assets/noori_title/english/4.png',
    'imageListAsset': 'Tera Naam Jab Lab Pe Jo',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/4.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Peer Noori',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Peer_Noori/',
    'imageAsset': 'assets/noori_title/english/5.png',
    'imageListAsset': 'Tu Shama Hai Mehfil Noorani',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Bargah-E-Mashkhiyath Panaa',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Ba_Bargahe_Mashiyath/',
    'imageAsset': 'assets/noori_title/english/6.png',
    'imageListAsset': 'Mai Bae Saro Saman Hun',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Noori/6.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Yaad-E-Shaikh',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Yaade_Shaik/',
    'imageAsset': 'assets/noori_title/english/7.png',
    'imageListAsset': 'Mai Aagaya Jisam Se Yaqeenan',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Noori/7.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Dyar-E-Noori Ko Rawangi Se Pehle',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Dayare_Noori_Ko_Rawangi_se_Pehile/',
    'imageAsset': 'assets/noori_title/english/8.png',
    'imageListAsset': 'Tamanna Hai Ab Jaake Jis',
    'artistPaths': {},
    'appBarTitle': 'Munaqib-E-Noori',
  },
  {
    'title': 'Aye Eind Laib Chalke Chale Din Bahar Ke',
    'firebaseImagePath': 'kalam/English/Munaqib_e_Noori/Ay_Andalib_Chal_Ke/',
    'imageAsset': 'assets/noori_title/english/9.png',
    'imageListAsset': 'Kahin Ruk Gaye Kahin Se Haate',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Noori/9.mp3'},
    'appBarTitle': 'Munaqib-E-Noori',
  },
];
