/* final List<Map<String, dynamic>> trackData = [
  {
    'title': 'Mazhar-E-Haqq',
    'firebaseImagePath': 'kalam/English/Naat/Mazhar_e_haq/',
    'imageAsset': 'assets/naat_title/english/1.png',
    'imageListAsset': 'assets/naat_list/english/1.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/1.mp3',
      'Imran': 'kalam/Audios/Imran/naat/1.mp3',
      'Arif': 'kalam/Audios/Arif/naat/1.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Anwar-E-Mohammed ﷺ',
    'firebaseImagePath': 'kalam/English/Naat/Anwar_e_mohammed/',
    'imageAsset': 'assets/naat_title/english/2.png',
    'imageListAsset': 'assets/naat_list/english/2.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/2.mp3',
      'Imran': 'kalam/Audios/Imran/naat/2.mp3',
      'Arif': 'kalam/Audios/Arif/naat/2.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Khaasaye Khaasan-E-Rusul',
    'firebaseImagePath': 'kalam/English/Naat/Khasaye_khasaane_rusul/',
    'imageAsset': 'assets/naat_title/english/3.png',
    'imageListAsset': 'assets/naat_list/english/3.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/3.mp3',
      'Imran': 'kalam/Audios/Imran/naat/3.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Armaghan-E-Naat',
    'firebaseImagePath': 'kalam/English/Naat/Irghamaan_e_naat/',
    'imageAsset': 'assets/naat_title/english/4.png',
    'imageListAsset': 'assets/naat_list/english/4.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/4.mp3',
      'Imran': 'kalam/Audios/Imran/naat/4.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Madeene Wale',
    'firebaseImagePath': 'kalam/English/Naat/Madeene_waale/',
    'imageAsset': 'assets/naat_title/english/5.png',
    'imageListAsset': 'assets/naat_list/english/5.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/5.mp3',
      'Imran': 'kalam/Audios/Imran/naat/5.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Tajdar-E-Madeena',
    'firebaseImagePath': 'kalam/English/Naat/Taajdaare_madina/',
    'imageAsset': 'assets/naat_title/english/6.png',
    'imageListAsset': 'assets/naat_list/english/6.png',
    'artistPaths': {},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Meraaj-E-Abdiyath',
    'firebaseImagePath': 'kalam/English/Naat/Meraaj_e_abdiyath/',
    'imageAsset': 'assets/naat_title/english/7.png',
    'imageListAsset': 'assets/naat_list/english/7.png',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/7.mp3',
      'Imran': 'kalam/Audios/Imran/naat/7.mp3',
      'Arif': 'kalam/Audios/Arif/naat/7.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Sahib-E-Laulaak ﷺ',
    'firebaseImagePath': 'kalam/English/Naat/Saahibe_laulaak/',
    'imageAsset': 'assets/naat_title/english/8.png',
    'imageListAsset': 'assets/naat_list/english/8.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/naat/8.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Sarapa Noor',
    'firebaseImagePath': 'kalam/English/Naat/Sarapa_noor/',
    'imageAsset': 'assets/naat_title/english/9.png',
    'imageListAsset': 'assets/naat_list/english/9.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/naat/9.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Aye Sayyadi Mukhtaar',
    'firebaseImagePath': 'kalam/English/Naat/Ay_sayyade_mukhtaar/',
    'imageAsset': 'assets/naat_title/english/10.png',
    'imageListAsset': 'assets/naat_list/english/10.png',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/naat/10.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Mai Waari Tum Par Jaon Nabiji',
    'firebaseImagePath': 'kalam/English/Naat/Mai_wari_tumpar_jawoon_nabi_ji/',
    'imageAsset': 'assets/naat_title/english/11.png',
    'imageListAsset': 'assets/naat_list/english/11.png',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/naat/11.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
];
 */
final List<Map<String, dynamic>> trackData = [ 
  {
    'title': 'Mazhar-E-Haqq',
    'firebaseImagePath': 'kalam/English/Naat/Mazhar_e_haq/',
    'imageAsset': 'assets/naat_title/english/1.png',
    'imageListAsset': 'Har Manzare Aalam Mai Nazar',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/1.mp3',
      'Imran': 'kalam/Audios/Imran/naat/1.mp3',
      'Arif': 'kalam/Audios/Arif/naat/1.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Anwar-E-Mohammed ﷺ',
    'firebaseImagePath': 'kalam/English/Naat/Anwar_e_mohammed/',
    'imageAsset': 'assets/naat_title/english/2.png',
    'imageListAsset': 'Dil Mai Hai Basi Mere',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/2.mp3',
      'Imran': 'kalam/Audios/Imran/naat/2.mp3',
      'Arif': 'kalam/Audios/Arif/naat/2.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Khaasaye Khaasan-E-Rusul',
    'firebaseImagePath': 'kalam/English/Naat/Khasaye_khasaane_rusul/',
    'imageAsset': 'assets/naat_title/english/3.png',
    'imageListAsset': 'Muhammed Mustafa Ka Naam',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/3.mp3',
      'Imran': 'kalam/Audios/Imran/naat/3.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Armaghan-E-Naat',
    'firebaseImagePath': 'kalam/English/Naat/Irghamaan_e_naat/',
    'imageAsset': 'assets/naat_title/english/4.png',
    'imageListAsset': 'Kise Boloun Ke Halat Kya Bani',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/4.mp3',
      'Imran': 'kalam/Audios/Imran/naat/4.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Madeene Wale',
    'firebaseImagePath': 'kalam/English/Naat/Madeene_waale/',
    'imageAsset': 'assets/naat_title/english/5.png',
    'imageListAsset': 'Jaan Tum Par Karun Qurban',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/5.mp3',
      'Imran': 'kalam/Audios/Imran/naat/5.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Tajdar-E-Madeena',
    'firebaseImagePath': 'kalam/English/Naat/Taajdaare_madina/',
    'imageAsset': 'assets/naat_title/english/6.png',
    'imageListAsset': 'Humari Taraf Bhi Madeene Ke',
    'artistPaths': {},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Meraaj-E-Abdiyath',
    'firebaseImagePath': 'kalam/English/Naat/Meraaj_e_abdiyath/',
    'imageAsset': 'assets/naat_title/english/7.png',
    'imageListAsset': 'Meri Jaan Tum Par Fidaa Hai',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/naat/7.mp3',
      'Imran': 'kalam/Audios/Imran/naat/7.mp3',
      'Arif': 'kalam/Audios/Arif/naat/7.mp3',
    },
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Sahib-E-Laulaak ﷺ',
    'firebaseImagePath': 'kalam/English/Naat/Saahibe_laulaak/',
    'imageAsset': 'assets/naat_title/english/8.png',
    'imageListAsset': 'Mera Zikr-O-Subha-O-Masaa',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/naat/8.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Sarapa Noor',
    'firebaseImagePath': 'kalam/English/Naat/Sarapa_noor/',
    'imageAsset': 'assets/naat_title/english/9.png',
    'imageListAsset': 'Mera Noor Wala Vo Pyaara',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/naat/9.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Aye Sayyadi Mukhtaar',
    'firebaseImagePath': 'kalam/English/Naat/Ay_sayyade_mukhtaar/',
    'imageAsset': 'assets/naat_title/english/10.png',
    'imageListAsset': 'Tere Jood-O-Karam Ne Mujhko',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/naat/10.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
  {
    'title': 'Mai Waari Tum Par Jaon Nabiji',
    'firebaseImagePath': 'kalam/English/Naat/Mai_wari_tumpar_jawoon_nabi_ji/',
    'imageAsset': 'assets/naat_title/english/11.png',
    'imageListAsset': 'Tham Lo Naiya Hamari Mai Wari',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/naat/11.mp3'},
    'appBarTitle': 'Naat-e-Nabi ﷺ',
  },
];
