final List<Map<String, dynamic>> trackData = [
  {
    'title': 'HAMD E BAEHAD',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Hamde_Behad/',
    'imageAsset': 'assets/kalam_title/english/1.png',
    'imageListAsset': 'Jidhar Bhi Hai Nazar Daali',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/1.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/1.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/1.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'MAST-E-ALAST',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/MasteAlast/',
    'imageAsset': 'assets/kalam_title/english/2.png',
    'imageListAsset': 'Tumhari Yaad Hai Tum Ho',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/2.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/2.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/2.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'NOOR-O-ZUHOOR',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Noor_o_zuhoor/',
    'imageAsset': 'assets/kalam_title/english/3.png',
    'imageListAsset': "Maki'n Tum Ho Maka'n Tum Ho",
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/3.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/3.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'RAAZ HI RAAZ',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Raaz_hi_raaz/',
    'imageAsset': 'assets/kalam_title/english/4.png',
    'imageListAsset': 'Meri Aankhon Mai Tum Ho',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/4.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/4.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/4.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HAAL E BISMIL',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/HaaleBismil/',
    'imageAsset': 'assets/kalam_title/english/5.png',
    'imageListAsset': 'Tumhi Par Raat Din Shayda',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/5.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/5.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/5.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'JAZB-O-SULOOK',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Jazbo_sulook/',
    'imageAsset': 'assets/kalam_title/english/6.png',
    'imageListAsset': 'Ye Zindagi Tumhari Hai',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/6.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/6.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/6.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KHAYAL-E-YAAR',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Khayaal_e_Yaar/',
    'imageAsset': 'assets/kalam_title/english/7.png',
    'imageListAsset': 'Mujhe Unki Yaad Hai Raat Din',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/7.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/7.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/7.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': "FAIZAN-E-BAARI TAA'AL",
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Faizaan_e_Bari_Tala/',
    'imageAsset': 'assets/kalam_title/english/8.png',
    'imageListAsset': 'Ye Koun-O-Makaa Saraa',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/8.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/8.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/8.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'BARQ-E-TAJALLI',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Barqe_tajalli/',
    'imageAsset': 'assets/kalam_title/english/9.png',
    'imageListAsset': "Do Jahaa'n Ko Koun Puche",
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/9.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/9.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'SHARAB-E-IRFAAN',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Sharaabe_Irfan/',
    'imageAsset': 'assets/kalam_title/english/10.png',
    'imageListAsset': 'Sambhal Sambhal Kar Tumhi Se Puchoon',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/10.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/10.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/10.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KIMIYAE HASTHI',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Kimiya_e_Hasti/',
    'imageAsset': 'assets/kalam_title/english/11.png',
    'imageListAsset': 'Zaraa Veham Ka Apne Parda',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/11.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'TASVEER-E-JAANA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Tasveer_e_janan/',
    'imageAsset': 'assets/kalam_title/english/12.png',
    'imageListAsset': 'Humari Ab Nigahhoon Mai Basi',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/12.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'JAANE TAMANNA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Jaane_tamanna/',
    'imageAsset': 'assets/kalam_title/english/13.png',
    'imageListAsset': 'Tum Dil Ke Makki Ho Dil Bhi Ho',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/13.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'ZAUQ-E-ZINDAGANI',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Zauqe_zindagani/',
    'imageAsset': 'assets/kalam_title/english/14.png',
    'imageListAsset': 'Tumhari Yaad Mai Ab Zauq-E-Zindagaani',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/14.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KHALWAT-E-DAR ANJUMAN',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/khalwat_e_dar_anjuman/',
    'imageAsset': 'assets/kalam_title/english/15.png',
    'imageListAsset': 'Jab Apni Khuli Aankhien Janana',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/15.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'JAAMA-E-ASDADH',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Jamiye_azdaad/',
    'imageAsset': 'assets/kalam_title/english/16.png',
    'imageListAsset': 'Kya Ajab Hai Sab Mai Reh Kar',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'TARQ-E-ALAYAQ',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Tarke_alayeq/',
    'imageAsset': 'assets/kalam_title/english/17.png',
    'imageListAsset': 'Sabse Ab Choot Kar Hum',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'NAASHAN-E-MANZIL',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Nishaane_manzil/',
    'imageAsset': 'assets/kalam_title/english/18.png',
    'imageListAsset': 'Parda Karte Bhi Ho Aur',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/18.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KUCH ISHAARAY',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Kuch_ishare/',
    'imageAsset': 'assets/kalam_title/english/19.png',
    'imageListAsset': 'Khud Se Hum Khud Kho',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/19.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'BAE HAMTA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Be_hamta/',
    'imageAsset': 'assets/kalam_title/english/20.png',
    'imageListAsset': 'Saare Aalam Mai Tumhari Zaat Ka',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/20.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HIJAAB-E-NOOR',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Hijaabe_noor/',
    'imageAsset': 'assets/kalam_title/english/21.png',
    'imageListAsset': 'Jisko Tumhara Ho Pataa',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/21.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'ISHQ-O-IRFAAN',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Ishq_o_irfaan/',
    'imageAsset': 'assets/kalam_title/english/22.png',
    'imageListAsset': 'Mujhe Yaad Hai Tumhari Mujhe',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/22.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'MAREEZ-E-ISHQ',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Mareez_e_ishq/',
    'imageAsset': 'assets/kalam_title/english/23.png',
    'imageListAsset': 'Kise Sunaon Ke Dil Ko Mere',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HARF-O-HIKAYATH',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Harfo_hikayath/',
    'imageAsset': 'assets/kalam_title/english/24.png',
    'imageListAsset': 'Jo Rahaa Ho Tere Khayal Mai',
    'artistPaths': {'Arif': 'kalam/Audios/Arif/Ishq/24.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'AZAAIEM',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Azaayem/',
    'imageAsset': 'assets/kalam_title/english/25.png',
    'imageListAsset': 'Na Dekhe Huwe Jo Hai',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/25.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HAMD-O-SHUKR',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Hamdo_shukr/',
    'imageAsset': 'assets/kalam_title/english/26.png',
    'imageListAsset': 'Tere Fazl Ka Meri Zaat Par',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/26.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'MAYEYAT-E-ELLA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Mayiyate_elaah/',
    'imageAsset': 'assets/kalam_title/english/27.png',
    'imageListAsset': 'Tera Saath Rehna Mera Wazu',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': "RAABI'T-E-MOHKAM",
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Rabte_muhkum/',
    'imageAsset': 'assets/kalam_title/english/28.png',
    'imageListAsset': 'Nigah Aalam Se Peher Li Hai',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/28.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/28.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HUWAS SAMI-UL-BASEER',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Howas_sami_ul_baseer/',
    'imageAsset': 'assets/kalam_title/english/29.png',
    'imageListAsset': 'Tumhi Sun Ne Waale Tumhi',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'MUQHTAAR-E-GHANI',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Muqtare_ghani/',
    'imageAsset': 'assets/kalam_title/english/30.png',
    'imageListAsset': 'Tum Jo Chahoo To Miya Kya',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/30.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'DAULATH-E-JAAWID',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Daulat_e_jaweed/',
    'imageAsset': 'assets/kalam_title/english/31.png',
    'imageListAsset': 'Tum Agar Mere Raho Bas',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/31.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KAIF-E-ITLAAQ',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Kaif_e_etlaaq/',
    'imageAsset': 'assets/kalam_title/english/32.png',
    'imageListAsset': 'Dil To Tumne Liya Jism Tabae',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/32.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/32.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'TAALIB-E-MOULA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Talib_e_moula/',
    'imageAsset': 'assets/kalam_title/english/33.png',
    'imageListAsset': 'Humse Tum Razi Raho Saath',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/33.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/33.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'TARJUMANI JAZBAATH',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Tarjuman_e_jazbaati/',
    'imageAsset': 'assets/kalam_title/english/34.png',
    'imageListAsset': 'Dil Mai Tumhari Yaad Lab Pe',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'TAAMIR-E-HAYATH',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Taamire_hayat/',
    'imageAsset': 'assets/kalam_title/english/35.png',
    'imageListAsset': 'Tumhari Raah Ki Taqreeb Bhi',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KHWAB SE HAQEEQATH TAK',
    'firebaseImagePath':
        'kalam/English/Ishq_o_maarifat/Khaab_se_haqiqath_tak_talak/',
    'imageAsset': 'assets/kalam_title/english/36.png',
    'imageListAsset': "Ye Jahaa'n Ki Saari Haqeetien",
    'artistPaths': {
      'Arif': 'kalam/Audios/Arif/Ishq/36.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'TALAB-E-HAQQ',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Taalib_e_huq/',
    'imageAsset': 'assets/kalam_title/english/37.png',
    'imageListAsset': 'Musibat Bhi Teri Khatir Mujhe',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/37.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'YAFT-O-SHUHOOD',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Yaaft_o_shuhood/',
    'imageAsset': 'assets/kalam_title/english/38.png',
    'imageListAsset': 'Meri Aankhon Mai Tuuhi Aagaya',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'RAZA BARR KHAZA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Raza_bar_khaza/',
    'imageAsset': 'assets/kalam_title/english/39.png',
    'imageListAsset': 'Kya Mujh Ko Kami Hogi Mera',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/39.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'KARAM DAR KARAM',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Karam_dar_karam/',
    'imageAsset': 'assets/kalam_title/english/40.png',
    'imageListAsset': 'Mujh Jaise Buray Par Babae',
    'artistPaths': {'Arif': 'kalam/Audios/Arif/Ishq/40.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'RAAZ-E-TADBER',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Raaz_e_tadabeer/',
    'imageAsset': 'assets/kalam_title/english/41.png',
    'imageListAsset': 'Khudaa Ka Fazl Hota Hai To',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/41.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/41.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HAQAIQ',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Haqayeq/',
    'imageAsset': 'assets/kalam_title/english/42.png',
    'imageListAsset': 'Uss Waqt Se Hoon Dewana Tera',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/42.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/42.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'CHASM-E-BEENA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Chashme_beena/',
    'imageAsset': 'assets/kalam_title/english/43.png',
    'imageListAsset': 'Apni Nisbat Aur Hai',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/43.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'AKS-O-AAINA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Aks_wo_aayina/',
    'imageAsset': 'assets/kalam_title/english/44.png',
    'imageListAsset': 'Hai Nazar Mai Tuuhi Tu',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/44.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/44.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'HUSN-E-KAR FARMA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Husn_kar_farma/',
    'imageAsset': 'assets/kalam_title/english/45.png',
    'imageListAsset': 'Wajood Tumne Diya Na Hota',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/45.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/45.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/45.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'SIRAAJ-E-MUNEER',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Siraj_e_muneer/',
    'imageAsset': 'assets/kalam_title/english/46.png',
    'imageListAsset': 'Tumhari Yaad Ka Har Dum',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/46.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'SARMAY-E-HAYATH',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Sarmaye_hayath/',
    'imageAsset': 'assets/kalam_title/english/47.png',
    'imageListAsset': 'Ab Zindagi Mai Raat Din Tera He',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/47.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/47.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'FANNA-O-BAQAA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Fana_wo_baqa/',
    'imageAsset': 'assets/kalam_title/english/48.png',
    'imageListAsset': 'Khudrath Khudaa Ki Hai Jo',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/48.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'NAFS-E-MUTMAENNA',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Nafse_mutmainna/',
    'imageAsset': 'assets/kalam_title/english/49.png',
    'imageListAsset': 'Sab Ye Khudrath Ke Hai Jalwe',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/49.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'EHWAL-E-KALEEMI',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Ahwaale_kalimi/',
    'imageAsset': 'assets/kalam_title/english/50.png',
    'imageListAsset': 'Nigah-E-Lutf Hoo Jaaye',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/50.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'DAWAM-E-HUZOOR',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Dawaame_huzoor/',
    'imageAsset': 'assets/kalam_title/english/51.png',
    'imageListAsset': 'Mere Saath Jab Hai Mera Khuda',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/51.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/51.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'RASHK-E-SIKANDARI',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Rashke_sikandari/',
    'imageAsset': 'assets/kalam_title/english/52.png',
    'imageListAsset': 'Tere Baghair Saakhiyaan',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/52.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/52.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/52.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'ALTAF-E-HUSAN',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Iltefaat_e_husn/',
    'imageAsset': 'assets/kalam_title/english/53.png',
    'imageListAsset': 'Tumhari Yaad Mai Hum Khud',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/53.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'JAAN-E-FARHING',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Jaan_e_farhing/',
    'imageAsset': 'assets/kalam_title/english/54.png',
    'imageListAsset': 'Kisi Ka Aain Haq Hona',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/54.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Ishq-E-Mohtabarr',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Ishq_e_mutabar/',
    'imageAsset': 'assets/kalam_title/english/55.png',
    'imageListAsset': 'Kya Hoga Dil Mera Bataa',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/55.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Umeed-E-Karam',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Ummeed_e_karam/',
    'imageAsset': 'assets/kalam_title/english/56.png',
    'imageListAsset': 'Mere Haal E Zaar Aye Khudaa',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/56.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/56.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Ya Kareem',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Yaa_kareem/',
    'imageAsset': 'assets/kalam_title/english/57.png',
    'imageListAsset': 'Mujrim Nahi Hai Mujhsa Daata',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/57.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/57.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': "Apna Ta'arruf",
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Apna_taruf/',
    'imageAsset': 'assets/kalam_title/english/58.png',
    'imageListAsset': 'Bazaahir Jee Raha Hun Dar',
    'artistPaths': {'Imran': 'kalam/Audios/Imran/Ishq/58.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Tark-E-Azbaab',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Tarke_asbaab/',
    'imageAsset': 'assets/kalam_title/english/59.png',
    'imageListAsset': 'Fazl Hi Ka Natija Hai',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/59.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/59.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': "Hairatoo'n Ka Safar",
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Hairatoon_ka_safar/',
    'imageAsset': 'assets/kalam_title/english/60.png',
    'imageListAsset': 'Siwa Iss Zindagi Ke Aa',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/60.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Humko Milna Hai Bas Unse',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Lillaahiyath/',
    'imageAsset': 'assets/kalam_title/english/61.png',
    'imageListAsset': 'Humko Milna Hai Bas Unse',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/61.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/61.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Fazl-E-Haq Se Aaj Tak',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Shukr_sad_shukr/',
    'imageAsset': 'assets/kalam_title/english/62.png',
    'imageListAsset': 'Fazl-E-Haq Se Aaj Tak',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Hum Ko Baatein Banani Aati',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Faizaane_mohabbath/',
    'imageAsset': 'assets/kalam_title/english/63.png',
    'imageListAsset': 'Hum Ko Baatein Banani Aati',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/63.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Mere Amal Ka Na Maloom',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Shukre_nemath/',
    'imageAsset': 'assets/kalam_title/english/64.png',
    'imageListAsset': 'Mere Amal Ka Na Maloom',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/64.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Kuch Sun Bhi Le Hamari',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Dua/',
    'imageAsset': 'assets/kalam_title/english/65.png',
    'imageListAsset': 'Kuch Sun Bhi Le Hamari',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/65.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Mazak-E-Zindagi Ko Ab',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Lahaye_amal/',
    'imageAsset': 'assets/kalam_title/english/66.png',
    'imageListAsset': 'Mazak-E-Zindagi Ko Ab',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/66.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Ghaflat Se Nikal Kuch Kaam',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Talqeene_khabar/',
    'imageAsset': 'assets/kalam_title/english/67.png',
    'imageListAsset': 'Ghaflat Se Nikal Kuch Kaam',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Bahut Kuch Kho Diya Hai',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Fikre_firda/',
    'imageAsset': 'assets/kalam_title/english/68.png',
    'imageListAsset': 'Bahut Kuch Kho Diya Hai',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Aye Bande Momin Tu Ek',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Muwaa_ize_hasna/',
    'imageAsset': 'assets/kalam_title/english/69.png',
    'imageListAsset': 'Aye Bande Momin Tu Ek',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Paresha’n Ho Na Bande Har',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Lutfe_zindagi/',
    'imageAsset': 'assets/kalam_title/english/70.png',
    'imageListAsset': 'Paresha’n Ho Na Bande Har',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Gham Na Kar Wehshat Na Kha',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Dawate_haq/',
    'imageAsset': 'assets/kalam_title/english/71.png',
    'imageListAsset': 'Gham Na Kar Wehshat Na Kha',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/71.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Aage Baadh Peeche Na Hatt',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Irtiqa/',
    'imageAsset': 'assets/kalam_title/english/72.png',
    'imageListAsset': 'Aage Baadh Peeche Na Hatt',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/72.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Wafaa Ka Kaam Kahan Jab',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Bayaan_e_wafa/',
    'imageAsset': 'assets/kalam_title/english/73.png',
    'imageListAsset': 'Wafaa Ka Kaam Kahan Jab',
    'artistPaths': {'Danish': 'kalam/Audios/Danish/Ishq/73.mp3'},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Huwaa Fazl Hum Pe To',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Ahwaale_sulook/',
    'imageAsset': 'assets/kalam_title/english/74.png',
    'imageListAsset': 'Huwaa Fazl Hum Pe To',
    'artistPaths': {},
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
  {
    'title': 'Jidhar Dekho Udhar Jalwa Numa',
    'firebaseImagePath': 'kalam/English/Ishq_o_maarifat/Sair_fil_wajood/',
    'imageAsset': 'assets/kalam_title/english/75.png',
    'imageListAsset': 'Jidhar Dekho Udhar Jalwa Numa',
    'artistPaths': {
      'Danish': 'kalam/Audios/Danish/Ishq/75.mp3',
      'Imran': 'kalam/Audios/Imran/Ishq/75.mp3',
      'Arif': 'kalam/Audios/Arif/Ishq/75.mp3',
    },
    'appBarTitle': 'Ishq-o-Marifat, Pind-o-Mouzat',
  },
];
